spring.application.name=backendAPI

# ======================
# SERVER
# ======================
server.port=8080

# ======================
# DATABASE (GLPI MySQL)
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/glpi
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# ======================
# JPA (مهم بزاف)
# ======================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANT: ما نبدلوش GLPI schema
spring.jpa.open-in-view=false

# ======================
# SECURITY (JWT)
# ======================
app.security.jwt.secret=change-this-to-a-long-random-secret-key-32-bytes-minimum
app.security.jwt.expiration-ms=86400000
